version: "{build}"
clone_depth: 1

cache:
    - c:\cargo\registry
    - c:\cargo\git
    - c:\projects\git-interactive-rebase-tool\target

init:
    - mkdir c:\cargo
    - mkdir c:\rustup
    - SET PATH=c:\cargo\bin;%PATH%

clone_folder: c:\projects\git-interactive-rebase-tool

environment:
    APPVEYOR: 1
    CARGO_HOME: "c:\\cargo"
    RUSTUP_HOME: "c:\\rustup"
    CARGO_TARGET_DIR: "c:\\projects\\git-interactive-rebase-tool\\target"
    global:
        PROJECT_NAME: git-interactive-rebase-tool
        RUST_BACKTRACE: full
    matrix:
        - TARGET: i686-pc-windows-gnu
          CHANNEL: stable
        - TARGET: i686-pc-windows-msvc
          CHANNEL: stable
        - TARGET: x86_64-pc-windows-gnu
          CHANNEL: stable
        - TARGET: x86_64-pc-windows-msvc
          CHANNEL: stable

matrix:
    fast_finish: true

install:
    - curl -sSf -o rustup-init.exe https://win.rustup.rs/
    - rustup-init.exe -y --default-host %TARGET% --no-modify-path
    - if defined MSYS2_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS2_BITS%\bin
    - rustc -V
    - cargo -V
    - curl -sSf -o PDCurses-3.4.tar.gz 'https://downloads.sourceforge.net/project/pdcurses/pdcurses/3.4/PDCurses-3.4.tar.gz'
    - tar vxf PDCurses-3.4.tar.gz
    - make -C PDCurses-3.4/win32/ -f gccwin32.mak WIDE=Y
    - mv PDCurses-3.4/win32/pdcurses.a PDCurses-3.4/win32/libpdcurses.a

test_script:
  - cargo test --verbose --all

before_deploy:
  - cargo build --release
  - mkdir staging
  - copy target\release\git-interactive-rebase-tool.exe staging
  - cd staging
  - 7z a ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip *
  - appveyor PushArtifact ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip

branches:
  only:
    - windows-build
